name: Yeet
options:
  minimumXcodeGenVersion: 2.40.0
  deploymentTarget:
    iOS: '15.0'
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ЗАМЕНИ_НА_СВОЙ_TEAM_ID # ВАЖНО: Убедись, что здесь твой реальный Team ID

targets:
  Yeet:
    type: application
    platform: iOS
    sources:
      # Исходный код
      - path: Sources/YeetApp
      - path: Sources/Shared
    resources:
      # Явно указываем, что Config.plist - это ресурс
      - path: Sources/Shared/Config.plist
    dependencies:
      - target: YeetShareExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atticdm.Yeet
        INFOPLIST_FILE: Sources/YeetApp/Info.plist
      attributes:
        SystemCapabilities:
          com.apple.ApplicationGroups.iOS:
            enabled: true
          com.apple.Keychain:
            enabled: true
    info:
      path: Sources/YeetApp/Info.plist
      properties:
        CFBundleDisplayName: Yeet
        CFBundleName: Yeet
        UILaunchScreen:
          UIColorName: White
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Light
        UIBackgroundModes: [fetch, processing]
        NSUserNotificationUsageDescription: "Yeet uses notifications to let you know when a background download completes."
    entitlements:
      path: Sources/YeetApp/Yeet.entitlements

  YeetShareExtension:
    type: app-extension
    platform: iOS
    sources:
      # Исходный код
      - path: Sources/YeetShareExtension
      - path: Sources/Shared
    resources:
      # И для расширения тоже указываем, что Config.plist - это ресурс
      - path: Sources/Shared/Config.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atticdm.Yeet.share
        INFOPLIST_FILE: Sources/YeetShareExtension/Info.plist
        LD_RUNPATH_SEARCH_PATHS: '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
      attributes:
        SystemCapabilities:
          com.apple.ApplicationGroups.iOS:
            enabled: true
          com.apple.Keychain:
            enabled: true
    info:
      path: Sources/YeetShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Yeet
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule: TRUEPREDICATE
            NSExtensionActivationSupportsWebURLWithMaxCount: 1
    entitlements:
      path: Sources/YeetShareExtension/YeetShareExtension.entitlements

schemes:
  Yeet:
    build:
      targets:
        Yeet: all
        YeetShareExtension: all
    run:
      config: Debug
