name: Yeet
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: '15.0'
packages: {}

settings:
  base:
    SWIFT_VERSION: 5.0
    # Add your Apple Developer Team ID here
    DEVELOPMENT_TEAM: # e.g., A1B2C3D4E5

targets:
  Yeet:
    type: application
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: Sources/YeetApp
      - path: Sources/Shared
    resources:
      - path: Config.plist
    dependencies:
      - target: YeetShareExtension
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atticdm.Yeet
        INFOPLIST_FILE: Sources/YeetApp/Info.plist
    info:
      path: Sources/YeetApp/Info.plist
      properties:
        CFBundleDisplayName: Yeet
        CFBundleName: Yeet
        UILaunchScreen:
          UIColorName: White
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIUserInterfaceStyle: Light
        UIBackgroundModes: [fetch, processing]
        NSUserNotificationUsageDescription: "Yeet uses notifications to let you know when a background download completes."
    entitlements:
      path: Sources/YeetApp/Yeet.entitlements

  YeetShareExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: '15.0'
    sources:
      - path: Sources/YeetShareExtension
      - path: Sources/Shared
    resources:
      - path: Config.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.atticdm.Yeet.share
        INFOPLIST_FILE: Sources/YeetShareExtension/Info.plist
        LD_RUNPATH_SEARCH_PATHS: '$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks'
    info:
      path: Sources/YeetShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Yeet
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule: TRUEPREDICATE
            NSExtensionActivationSupportsWebURLWithMaxCount: 1
    entitlements:
      path: Sources/YeetShareExtension/YeetShareExtension.entitlements

schemes:
  Yeet:
    build:
      targets:
        Yeet: all
        YeetShareExtension: all
    run:
      config: Debug
